body: |
  ### Release Notes

   - [Milestone]({milestone.html_url}?closed=1)  
      {milestone.description}
  
  {groups}

group: |
  ### {group.name}
  
  {issues}

issue: |
   - {issue.title} ([#{issue.number}]({issue.html_url}))  
      {issue.body}
empty: |
  - No release notes.
groups:
- name: Added
  state: all
  labels: Feature
- name: Changed
  state: all
  labels: Change
- name: Deprecated
  state: all
  labels: Deprecation
- name: Removed
  state: all
  labels: Remove
- name: Fixed
  state: all
  labels: Bug
- name: Security
  state: all
  labels: Security
