name: 'Milestone Changelog'
description: 'Creates changelog based on milestone.'
inputs:
  milestone:
    description: 'Milestone number or title.'
    required: true
  token:
    description: 'GitHub token used by action.'
    default: ${{ github.token }}
    required: true
  repository:
    description: 'Owner and repository name. For example, "Codertocat/Hello-World".'
    default: ${{ github.repository }}
    required: true
  config:
    description: 'Path to file or config as value with generate settings. (Possible representation types: "Json" or "Yaml".)'
    default: .github/milestone-changelog.yml
    required: true
  outputType:
    description: 'Type of result output, possible values "action", "file" or "all".'
    default: action
    required: true
  outputPath:
    description: 'Path of output file.'
    default: ${{ github.action }}
    required: true
outputs:
  result:
    description: 'Action result.'
runs:
  using: 'node12'
  main: 'dist/index.js'
